### PR TITLE
Fix SUID sandbox issue

### PR DESCRIPTION
**Pull request by l8nit3tr0ubl3**
-downgrade electron 4.2.8
-update electron-builder 21.2.0

should fix issue #56 without affecting windows or OSX builds.
Tested and working on:
-Ubuntu 16.04-19.04
-Debian Gnome 9 & 10
-Debian KDE 10
-Debian 10 Matte -by pioruns
-Windows 10
-OSX Mojave hackintosh

### CODE REVIEW

**Comment by Qrysto** [comment]
@l8nit3tr0ubl3 I see you created PRs that upgrades to Electron v6 then closed it and created this PR which downgrades to Electron v4. So have you tested with Electron v6 and did it work for you? Because we don't really want to downgrade Electron version at this point.

**Comment by l8nit3tr0ubl3** [comment]
Electron 6 fixes the issue for ubuntu based systems, however it persists on debian 9 and 10. When downgrading to 4.2.8 (while leaving the electron-builder updated to newest) both ubuntu and debian gnome distros work great.
Also tested and working on OSX and windows 10.
I Understand the downgrade is undesirable, but I don't believe 6.x is a viable option just yet untill it works cleanly across a majority of distros (just my 2 satoshi worth)..
I am still running/testing debian, ubuntu and windows 10 as we speak with no issues yet with 4.2.8 downgrade in place (except possible vulnerabilities from using an older version)

**Comment by Qrysto** [comment]
@l8nit3tr0ubl3 I don't have a Debian machine to test on and couldn't follow the issue very closely due to lack of time, but I found something might be the workaround for this: https://github.com/gcascio/electron-uns-workaround. Have you tried that solution?

**Comment by l8nit3tr0ubl3** [comment]
I have not, although I did see it. Honestly i assumed disabling the sandbox would be less preferable then a downgrade. Once I'm finished work I'll apply the fix to your original code and update with the results

**Comment by l8nit3tr0ubl3** [comment]
**UPDATE**
running `sysctl kernel.unprivileged_userns_clone=1` as root seems to bypass the issue while maintaining electron 5.x!! However, this should likely be applied by the user, as making kernel changes automatically without user knowledge (if this were to be coded into the wallet) could be seen as malware.

**Comment by l8nit3tr0ubl3** [comment]
Closing for now, as workaround should do until kernels are updated to include the option above at runtime.

**Comment by Qrysto** [comment]
@l8nit3tr0ubl3 Could you help me list out a list of Linux distros you know that need this workaround?

**Comment by l8nit3tr0ubl3** [comment]
So far as I've found, debian 9 and 10, all DE versions. I will setup some new VM's tonight and test as many distros as I can and get back to you with a list.
Always happy to help :)

**Comment by l8nit3tr0ubl3** [comment]
So far it looks like the big difference between ubuntu 18+ and Debian 9/10 is the kernel version. 

When building on ubuntu 18.04, I noticed a kernel version 5.x, whereas Debian 10 is 4.19.0. This could explain why the option is not enabled yet. So I would say any distro with kernel 5.x should work out of box.

**Working -no fix:**
-Ubuntu 18&19 - 5.0.0-23 & 
-Fedora newest - 5.0.9 kernel
-OpenMandriva newest - 5.1.9 kernel

**Needs kernel flag fix**
-Debian 9&10 - 4.19.0 kernel
-Gentoo newest - 4.5.2 kernel

**Other Issues**
-Archbang newest - kernel - missing libavahi-common.so.3
-Kali newest - 4.19.28 kernel - allows to accept license, creates .config folder ,quits with no output
-Gentoo - kernel - cannot execute binary file (AppImage) exec format error

**Pull request closed without merging**
